# Generated by Django 6.0.6 on 2026-07-13 19:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0002_rename_movie_review_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='name',
            new_name='movie',
        ),
    ]
