# Generated by Django 6.0.6 on 2026-07-03 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actors', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='actor',
            name='birthday',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='actor',
            name='nationality',
            field=models.CharField(blank=True, choices=[('ARG', 'Argentina'), ('AUS', 'Australia'), ('AUT', 'Austria'), ('BEL', 'Belgium'), ('BRA', 'Brazil'), ('CAN', 'Canada'), ('CHL', 'Chile'), ('CHN', 'China'), ('COL', 'Colombia'), ('CUB', 'Cuba'), ('DEU', 'Germany'), ('DNK', 'Denmark'), ('EGY', 'Egypt'), ('ESP', 'Spain'), ('FRA', 'France'), ('GBR', 'United Kingdom'), ('GRC', 'Greece'), ('IND', 'India'), ('IRL', 'Ireland'), ('ISR', 'Israel'), ('ITA', 'Italy'), ('JPN', 'Japan'), ('KOR', 'South Korea'), ('MEX', 'Mexico'), ('NLD', 'Netherlands'), ('NOR', 'Norway'), ('NZL', 'New Zealand'), ('POL', 'Poland'), ('PRT', 'Portugal'), ('RUS', 'Russia'), ('SWE', 'Sweden'), ('TUR', 'Turkey'), ('UKR', 'Ukraine'), ('USA', 'United States'), ('URY', 'Uruguay')], max_length=100, null=True),
        ),
    ]
